-- ALIVE v3.1 replacement expansion and evidence metadata

update public.replacements_catalog
set mechanism = coalesce(mechanism,
  case category
    when 'breath' then 'breathing' when 'movement' then 'movement' when 'drink' then 'drink'
    when 'food' then 'food' when 'nrt' then 'evidence_treatment' when 'meaning' then 'meaning'
    when 'orienting' then 'attention' when 'observation' then 'attention' when 'journal' then 'reflection'
    when 'contact' then 'social' when 'environment' then 'context_change' when 'music' then 'sensory'
    when 'rest' then 'pause' when 'reward' then 'reward' else 'ritual' end),
  evidence_level = coalesce(evidence_level, case when category='nrt' then 'A' when category in ('movement','breath') then 'B' else 'C' end),
  evidence_scope = coalesce(evidence_scope,
    case when category='nrt' then 'Доказательный инструмент прекращения курения; ALIVE не назначает дозировки'
         when category='movement' then 'Есть данные по кратковременному снижению тяги; не самостоятельная гарантия отказа'
         when category='breath' then 'Поддержка состояния/arousal; long-term smoking cessation outcome не установлен'
         else 'Поведенческая эвристика ALIVE; эффективность проверяется по личным outcomes' end);

update public.replacements_catalog
set eligibility = coalesce(eligibility,'{}'::jsonb) || jsonb_build_object('mechanism', mechanism, 'evidence_level', evidence_level);

update public.replacements_catalog
set source_title='WHO Clinical Treatment Guideline for Tobacco Cessation in Adults 2024',
    source_url='https://www.who.int/publications/i/item/9789240096431',
    evidence_level='A', mechanism='evidence_treatment',
    eligibility=coalesce(eligibility,'{}'::jsonb) || '{"mechanism":"evidence_treatment","evidence_level":"A"}'::jsonb
where code in ('nrt_spray','nrt_gum');

update public.replacements_catalog
set source_title='Physical activity and acute cigarette craving evidence',
    source_url='https://pubmed.ncbi.nlm.nih.gov/22585034/', evidence_level='B', mechanism='movement',
    eligibility=coalesce(eligibility,'{}'::jsonb) || '{"mechanism":"movement","evidence_level":"B"}'::jsonb
where category='movement';

update public.replacements_catalog
set source_title='Brief structured respiration practices and mood/arousal',
    source_url='https://pubmed.ncbi.nlm.nih.gov/36630953/', evidence_level='B', mechanism='breathing',
    eligibility=coalesce(eligibility,'{}'::jsonb) || '{"mechanism":"breathing","evidence_level":"B"}'::jsonb
where category='breath';

insert into public.replacements_catalog
(code,title,instruction,category,need_codes,product_types,eligibility,published,sort_order,icon,duration,summary,safety,mechanism,evidence_level,evidence_scope,source_title,source_url,context_tags,rotation_weight,intensity_min,intensity_max)
values
('ground_feet','Стопы в пол','Поставь обе стопы на пол и слегка прижми их к поверхности на 5 секунд. Отпусти и заметь вес тела. Повтори 3 раза.','grounding',array['release_tension','pause','switch','self_presence'],array['cigarette','hookah','vape'],'{"mechanism":"grounding","evidence_level":"C"}',true,201,'ground','40 сек','Вернуть внимание из автоматизма в ощущение опоры','Без боли и без задержки дыхания','grounding','C','Короткая self-regulation эвристика ALIVE, адаптированная из HumanOS',null,null,array['stress','anxiety','overload'],1.1,1,10),
('press_release','Надавить и отпустить','Ладони на бёдра или стопы в пол. Надави уверенно на 5 секунд и полностью отпусти. Сделай 4 повтора.','grounding',array['release_tension','switch','self_presence'],array['cigarette','hookah','vape'],'{"mechanism":"grounding","evidence_level":"C"}',true,202,'hands','45 сек','Коротко собрать границы тела и отпустить напряжение','Без боли; дыши обычно','grounding','C','Self-regulation эвристика ALIVE, адаптированная из HumanOS',null,null,array['stress','anger','anxiety'],1.0,1,10),
('five_long_exhales','Пять спокойных выдохов','Сделай обычный вдох и чуть более длинный мягкий выдох. Повтори пять раз, не стараясь дышать глубже обычного.','breath',array['release_tension','pause','switch'],array['cigarette','hookah','vape'],'{"mechanism":"breathing","evidence_level":"B"}',true,203,'breath','1 мин','Снизить внутреннее ускорение без сложной техники','Если кружится голова или неприятно — сразу вернись к обычному дыханию','breathing','B','Evidence относится к состоянию/arousal, а не к гарантии прекращения курения','Brief structured respiration practices and mood/arousal','https://pubmed.ncbi.nlm.nih.gov/36630953/',array['stress','anxiety'],1.2,1,10),
('attention_321','Три — два — один','Назови про себя 3 вещи, которые видишь, 2 звука вокруг и 1 ощущение в теле.','orienting',array['switch','release_tension','self_presence'],array['cigarette','hookah','vape'],'{"mechanism":"attention","evidence_level":"C"}',true,204,'eye','45 сек','Вернуть фокус в то, что происходит прямо сейчас','Не задерживайся на неприятном ощущении','attention','C','Attention-reset эвристика ALIVE, адаптированная из HumanOS',null,null,array['stress','thinking','phone'],1.1,1,10),
('focus_point','Одна спокойная точка','Выбери один неподвижный предмет и смотри на него 30–45 секунд. Заметь форму, свет и края, ничего не анализируя.','orienting',array['switch','pause','self_presence'],array['cigarette','hookah','vape'],'{"mechanism":"attention","evidence_level":"C"}',true,205,'eye','45 сек','Сузить входящий шум до одной простой задачи',null,'attention','C','Attention-reset эвристика ALIVE, адаптированная из HumanOS',null,null,array['overload','work','phone'],0.95,1,10),
('listen_three_sounds','Три звука вокруг','Остановись на полминуты и найди три разных звука: близкий, средний и дальний.','orienting',array['switch','pause','self_presence'],array['cigarette','hookah','vape'],'{"mechanism":"attention","evidence_level":"C"}',true,206,'eye','40 сек','Переключить внимание с тяги на окружающую среду',null,'attention','C','Поведенческая эвристика ALIVE',null,null,array['spontaneous','boredom','stress'],0.9,1,10),
('shoulder_release','Плечи и челюсть','Опусти плечи, разожми зубы и на несколько секунд отпусти язык от нёба. Сделай обычный спокойный выдох.','grounding',array['release_tension','pause'],array['cigarette','hookah','vape'],'{"mechanism":"grounding","evidence_level":"C"}',true,207,'calm','40 сек','Убрать часть незаметного мышечного напряжения','Не тянуть шею через боль','grounding','C','Self-regulation эвристика ALIVE',null,null,array['work','driving','stress'],1.0,1,10),
('walk_two_minutes','Две минуты пройтись','Встань и две минуты просто походи — по комнате, коридору или улице. Не тренировка, а смена состояния.','movement',array['switch','stimulation','release_tension','pause'],array['cigarette','hookah','vape'],'{"mechanism":"movement","evidence_level":"B"}',true,208,'walk','2 мин','Сменить контекст и дать телу короткое движение','Выбирай только привычную и безопасную нагрузку','movement','B','Есть smoking-specific evidence для кратковременного уменьшения craving','Physical activity and acute cigarette craving evidence','https://pubmed.ncbi.nlm.nih.gov/22585034/',array['work','boredom','stress','after_meal'],1.25,1,10),
('stairs_one_flight','Один пролёт','Если лестница тебе подходит, спокойно пройди один пролёт вверх и обратно.','movement',array['stimulation','switch'],array['cigarette','hookah','vape'],'{"mechanism":"movement","evidence_level":"B"}',true,209,'walk','2 мин','Коротко включить тело и сменить ритм','Пропусти при боли, одышке, головокружении или если нагрузка тебе не привычна','movement','B','Acute activity может снижать craving; конкретная дозировка ALIVE экспериментальна','Physical activity and acute cigarette craving evidence','https://pubmed.ncbi.nlm.nih.gov/22585034/',array['low_energy','work'],0.7,1,7),
('sparkling_water','Газированная вода','Сделай несколько маленьких глотков прохладной газированной воды и сосредоточься на ощущениях во рту.','drink',array['oral_sensory','switch','pleasure','pause'],array['cigarette','hookah','vape'],'{"mechanism":"drink","evidence_level":"C"}',true,210,'tea','1 мин','Яркий сенсорный ритуал без дыма',null,'drink','C','Поведенческая эвристика ALIVE',null,null,array['oral','after_meal','coffee'],0.9,1,10),
('gum_sugarfree','Жвачка без сахара','Возьми жвачку без сахара и на минуту направь внимание на вкус и работу челюсти.','oral',array['oral_sensory','switch'],array['cigarette','hookah','vape'],'{"mechanism":"oral","evidence_level":"C"}',true,211,'leaf','2 мин','Занять рот без сигареты','Не использовать, если жевание вызывает боль или не подходит по здоровью','oral','C','Поведенческая эвристика ALIVE',null,null,array['driving','after_meal','coffee'],1.1,1,10),
('mint_reset','Мята','Возьми обычную мятную пастилку без никотина или освежи рот привычным безопасным способом.','oral',array['oral_sensory','switch','closure'],array['cigarette','hookah','vape'],'{"mechanism":"oral","evidence_level":"C"}',true,212,'leaf','1 мин','Сменить вкус и завершить старый ритуал',null,'oral','C','Поведенческая эвристика ALIVE',null,null,array['after_meal','coffee'],0.9,1,10),
('brush_teeth','Почистить зубы','После еды или кофе почисти зубы как новый знак: ритуал завершён.','ritual',array['closure','oral_sensory','switch'],array['cigarette','hookah','vape'],'{"mechanism":"context_change","evidence_level":"C"}',true,213,'finish','2 мин','Заменить привычную точку «еда → сигарета» другой точкой','Следуй обычным правилам ухода за зубами','context_change','C','Cue-restructuring эвристика ALIVE',null,null,array['after_meal','coffee'],1.15,1,10),
('hands_pen','Занять руки','Возьми ручку или небольшой безопасный предмет и минуту крути, рисуй линии или делай простые пометки.','manual',array['oral_sensory','switch','pause'],array['cigarette','hookah','vape'],'{"mechanism":"manual","evidence_level":"C"}',true,214,'hands','1 мин','Убрать часть привычки «что-то держать в руке»','Не использовать острые или опасные предметы','manual','C','Поведенческая эвристика ALIVE',null,null,array['work','phone','boredom'],0.95,1,10),
('apple_crunch','Яблоко','Если ты действительно голоден, съешь небольшое яблоко и не торопись.','food',array['oral_sensory','pleasure','stimulation'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,220,'leaf','3 мин','Хрустящий вариант, когда тяга совпала с голодом',null,'food','C','Пищевая эвристика ALIVE; не использовать как автоматический ответ на каждую тягу',null,null,array['hunger','oral'],0.8,1,10),
('pear_crunch','Груша','Если голод есть, выбери небольшую грушу как одну порцию, а не как обязательное заедание тяги.','food',array['oral_sensory','pleasure'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,221,'leaf','3 мин','Сочный хрустящий вариант при реальном голоде',null,'food','C','Пищевая эвристика ALIVE',null,null,array['hunger','oral'],0.75,1,10),
('carrot_crunch','Морковь','Если хочется именно пожевать и ты голоден, возьми небольшую порцию моркови.','food',array['oral_sensory','stimulation'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,222,'leaf','3 мин','Хрустящая несладкая альтернатива',null,'food','C','Пищевая эвристика ALIVE',null,null,array['hunger','oral'],0.85,1,10),
('cucumber_crunch','Огурец','Небольшая порция свежего огурца, если тяга совпала с голодом или хочется хрустящего вкуса.','food',array['oral_sensory','pleasure'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,223,'leaf','3 мин','Лёгкая хрустящая альтернатива',null,'food','C','Пищевая эвристика ALIVE',null,null,array['hunger','oral'],0.8,1,10),
('sweet_pepper_crunch','Сладкий перец','Если голод есть, съешь небольшую порцию сладкого перца и обрати внимание на вкус и хруст.','food',array['oral_sensory','pleasure'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,224,'leaf','3 мин','Яркий несигаретный вкус при реальном голоде',null,'food','C','Пищевая эвристика ALIVE',null,null,array['hunger','oral'],0.8,1,10),
('berries_portion','Небольшая порция ягод','Если ты голоден, выбери небольшую порцию ягод и ешь без телефона.','food',array['pleasure','oral_sensory'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,225,'leaf','3 мин','Яркий вкус без автоматического перекуса',null,'food','C','Пищевая эвристика ALIVE',null,null,array['hunger','oral'],0.7,1,10),
('plain_yogurt','Натуральный йогурт','Если есть голод, выбери небольшую порцию натурального йогурта.','food',array['pleasure','oral_sensory'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,226,'leaf','4 мин','Более насыщающий вариант при реальном голоде','Учитывай личную переносимость молочных продуктов','food','C','Пищевая эвристика ALIVE',null,null,array['hunger'],0.7,1,10),
('cottage_cheese','Творог','Если тяга совпала с голодом, выбери небольшую привычную порцию творога.','food',array['pleasure','oral_sensory'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,227,'leaf','4 мин','Сытный вариант вместо случайного сладкого перекуса','Учитывай личную переносимость молочных продуктов','food','C','Пищевая эвристика ALIVE',null,null,array['hunger'],0.65,1,10),
('egg_portion','Яйцо','Если сейчас именно голод, а не только тяга, выбери одно привычно приготовленное яйцо.','food',array['stimulation','oral_sensory'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,228,'leaf','5 мин','Небольшая белковая еда при реальном голоде','Не использовать при индивидуальных ограничениях','food','C','Пищевая эвристика ALIVE',null,null,array['hunger'],0.6,1,10),
('nuts_small','Небольшая порция орехов','Если голоден, возьми небольшую заранее отмеренную порцию орехов и убери упаковку.','food',array['oral_sensory','pleasure'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,229,'leaf','3 мин','Плотный вариант при голоде без бесконечного перекуса','Не использовать при аллергии; учитывать индивидуальные ограничения','food','C','Пищевая эвристика ALIVE',null,null,array['hunger'],0.6,1,10),
('phone_down_pause','Две минуты без экрана','Положи телефон экраном вниз и две минуты ничего не листай. Можно просто смотреть в окно или сидеть.','pause',array['pause','self_presence','release_tension','switch'],array['cigarette','hookah','vape'],'{"mechanism":"pause","evidence_level":"C"}',true,230,'pause','2 мин','Вернуть себе настоящую паузу вместо связки телефон + никотин',null,'pause','C','Поведенческая эвристика ALIVE',null,null,array['phone','work','evening'],1.1,1,10),
('gaze_far_minute','Минута смотреть вдаль','Посмотри в окно или на дальний объект около минуты. Ничего не решай в это время.','orienting',array['pause','switch','self_presence'],array['cigarette','hookah','vape'],'{"mechanism":"attention","evidence_level":"C"}',true,231,'eye','1 мин','Сменить зрительный фокус и дать мозгу короткую паузу',null,'attention','C','Поведенческая эвристика ALIVE',null,null,array['work','phone','overload'],0.95,1,10),
('write_real_need','Одна строка о том, что нужно','Напиши одну строку: «Сейчас я хочу от сигареты…» и закончи фразу без анализа.','journal',array['meaning','release_tension','pause','switch','closure'],array['cigarette','hookah','vape'],'{"mechanism":"reflection","evidence_level":"C"}',true,232,'journal','1 мин','Отделить функцию от привычной формы ритуала',null,'reflection','C','Поведенческая эвристика ALIVE',null,null,array['stress','thinking','spontaneous'],1.0,1,10),
('focus_two_minutes','Две минуты одного дела','Выбери самый маленький следующий шаг и делай только его две минуты: открыть файл, написать первую строку, убрать один предмет.','focus',array['stimulation','switch','closure'],array['cigarette','hookah','vape'],'{"mechanism":"focus","evidence_level":"C"}',true,233,'focus','2 мин','Проверить, нужна ли сигарета или нужен был короткий старт',null,'focus','C','Поведенческая эвристика ALIVE',null,null,array['task_start','work','procrastination'],1.05,1,9),
('text_support','Одно сообщение человеку','Напиши человеку, которому доверяешь: «Сейчас сильная тяга, просто побудь со мной пару минут».','contact',array['connection','release_tension'],array['cigarette','hookah','vape'],'{"mechanism":"social","evidence_level":"C"}',true,234,'people','2 мин','Получить контакт напрямую, а не через общий ритуал курения','Только если это комфортный и заранее выбранный контакт','social','C','Поведенческая эвристика ALIVE',null,null,array['social','stress'],0.8,1,10)
on conflict (code) do update set
  title=excluded.title,instruction=excluded.instruction,category=excluded.category,need_codes=excluded.need_codes,
  product_types=excluded.product_types,eligibility=excluded.eligibility,published=true,sort_order=excluded.sort_order,
  icon=excluded.icon,duration=excluded.duration,summary=excluded.summary,safety=excluded.safety,
  mechanism=excluded.mechanism,evidence_level=excluded.evidence_level,evidence_scope=excluded.evidence_scope,
  source_title=excluded.source_title,source_url=excluded.source_url,context_tags=excluded.context_tags,
  rotation_weight=excluded.rotation_weight,intensity_min=excluded.intensity_min,intensity_max=excluded.intensity_max;
