-- ALIVE v3.1 Myths seed
insert into public.myths_catalog
(code,title,short_reframe,explanation,mechanism,evidence_level,evidence_scope,source_title,source_url,doi,trigger_codes,need_codes,product_types,context_tags,replacement_codes,published,sort_order,last_verified_at)
values
('calms_me','Сигарета меня успокаивает','Облегчение может быть реальным, но часть напряжения возникает из-за самой никотиновой зависимости между сигаретами','Никотиновый withdrawal может давать раздражительность, тревогу и внутреннее беспокойство. Следующая доза временно снимает часть этого состояния, поэтому цикл легко принять за лечение стресса.','negative_reinforcement','B','Withdrawal mechanism + mental-health cessation evidence','CDC — 7 Common Withdrawal Symptoms','https://www.cdc.gov/tobacco/campaign/tips/quit-smoking/7-common-withdrawal-symptoms/index.html',null,array['tension','anger','irritability','anxiety','uncertainty'],array['release_tension','pause'],array['cigarette','vape'],array['stress','anxiety'],array['five_long_exhales','ground_feet','walk_two_minutes'],true,10,'2026-08-16'),
('focus_better','С сигаретой я лучше соображаю','Никотин может временно снять трудности с концентрацией из-за отмены. Это не делает зависимость хорошим способом поддерживать фокус','Проблемы концентрации являются известным симптомом nicotine withdrawal. Полезно отделить снятие withdrawal от устойчивой способности сосредоточиться.','withdrawal_reversal','B','Withdrawal/concentration mechanism','CDC — 7 Common Withdrawal Symptoms','https://www.cdc.gov/tobacco/campaign/tips/quit-smoking/7-common-withdrawal-symptoms/index.html',null,array['work_computer','task_start','thinking'],array['stimulation','switch'],array['cigarette','vape'],array['focus','work'],array['focus_two_minutes','walk_two_minutes','water'],true,20,'2026-08-16'),
('only_real_pause','Сигарета — мой единственный настоящий отдых','Пауза тебе действительно нужна. Дым — не обязательная её часть','Курение часто объединяет разрешение остановиться, смену места, дыхательный ритм и никотин в один пакет. ALIVE сохраняет функцию паузы и меняет форму.','ritual_bundle','C','Behavioural decomposition hypothesis','ALIVE Method v1','https://github.com/wd7b3k/Alive/blob/main/docs/METHODOLOGY.md',null,array['task_transition','after_task','evening'],array['pause','solitude','self_presence'],array['cigarette','hookah','vape'],array['pause'],array['phone_down_pause','tea_pause','gaze_far_minute'],true,30,'2026-08-16'),
('coffee_needs_smoke','Кофе без сигареты уже не тот','Повторяемая пара «кофе → сигарета» может стать сильным сигналом. Сам кофе не требует продолжения этой цепочки','Environmental cues являются важными непосредственными antecedents lapse. Изменение места, последовательности или следующего действия помогает тестировать новую связку.','cue_association','B','EMA antecedent evidence; конкретная ALIVE замена экспериментальна','Perski et al. Addiction 2023','https://pubmed.ncbi.nlm.nih.gov/36807443/','10.1111/add.16173',array['coffee'],array['pleasure','closure','pause'],array['cigarette','vape'],array['coffee'],array['brush_teeth','tea_ritual','walk_two_minutes'],true,40,'2026-08-16'),
('meal_needs_smoke','После еды без сигареты будто не закончено','Ощущение завершения можно сохранить другим последним действием','Повторяемая последовательность может сделать сигарету привычной точкой завершения еды. Новый terminal action позволяет разорвать её без запрета на саму паузу.','cue_association','C','Cue-restructuring ALIVE hypothesis','ALIVE Method v1','https://github.com/wd7b3k/Alive/blob/main/docs/METHODOLOGY.md',null,array['after_meal'],array['closure','oral_sensory'],array['cigarette','vape'],array['after_meal'],array['brush_teeth','mint_reset','walk_two_minutes'],true,50,'2026-08-16'),
('smoking_is_style','Курить стильно','Рекламный образ легко отделить от дыма, запаха и реальных последствий для полости рта','ALIVE не спорит со вкусом и не стыдит человека. Мы только возвращаем в образ те физические эффекты курения, которые романтизация обычно убирает из кадра.','identity_expectancy','C','Identity reframe + factual health support','CDC — Tobacco Use and Oral Health Facts','https://www.cdc.gov/oral-health/data-research/facts-stats/fast-facts-tobacco-use-and-oral-health.html',null,array['social','hookah_venue'],array['pleasure','connection','meaning'],array['cigarette','hookah','vape'],array['identity','social'],array['meaning_read','meaning_card'],true,60,'2026-08-16'),
('social_helper','Курение помогает мне общаться','Общий выход и контакт могут быть приятны сами по себе. Сигарета не обязана быть пропуском в разговор','Социальные cues тесно связаны с lapse, но функцию общения можно закрывать напрямую.','social_cue','B','Environmental/social cue evidence','Perski et al. Addiction 2023','https://pubmed.ncbi.nlm.nih.gov/36807443/','10.1111/add.16173',array['social','hookah_venue'],array['connection'],array['cigarette','hookah','vape'],array['social'],array['text_support','stay_close'],true,70,'2026-08-16'),
('one_does_not_count','Одна сигарета почти не считается','Для сердца и сосудов риск не уменьшается линейно вместе с количеством сигарет','Большой meta-analysis cohort studies показал непропорционально высокий cardiovascular excess risk даже при примерно одной сигарете в день.','risk_minimization','A','Population cardiovascular risk; не индивидуальный прогноз','Hackshaw et al. BMJ 2018','https://www.bmj.com/content/360/bmj.j5855',null,array['spontaneous'],array['pleasure'],array['cigarette'],array['risk'],array['meaning_read'],true,80,'2026-08-16'),
('light_is_safer','Light безопаснее обычных сигарет','Маркировка light или low-tar не превращает сигарету в безопасную альтернативу','Низкие machine-measured tar/nicotine yields и маркетинговые descriptors исторически создавали ложное ощущение существенно меньшего риска.','risk_minimization','A','Authoritative tobacco-harm evidence','U.S. Surgeon General 2000 highlights','https://archive.cdc.gov/www_cdc_gov/tobacco/sgr/2000/highlights.html',null,array['other'],array['pleasure'],array['cigarette'],array['risk','product'],array[]::text[],true,90,'2026-08-16'),
('hookah_is_mild','Кальян мягче сигарет','Вода и аромат не делают кальян безопасной альтернативой','CDC указывает, что вода не фильтрует токсичные вещества дыма до безопасного уровня, а уголь добавляет carbon monoxide и другие токсиканты.','harm_minimization','A','Authoritative public-health evidence','CDC — Hookahs','https://www.cdc.gov/tobacco/other-tobacco-products/hookahs.html',null,array['hookah_venue','social'],array['pleasure','connection'],array['hookah'],array['hookah','risk'],array[],true,95,'2026-08-16'),
('nrt_same_as_smoking','НЗТ — почти то же самое, что курить','Никотин остаётся никотином, но сигаретный дым добавляет токсичные продукты горения. НЗТ намного безопаснее продолжения курения','NRT доставляет nicotine без сигаретного combustion smoke и используется как доказательная помощь при отказе.','treatment_misconception','A','Cessation medication safety','CDC — Quit Medicines Are Much Safer Than Smoking','https://www.cdc.gov/tobacco/campaign/tips/quit-smoking/quit-smoking-medications/3-reasons-to-use-medicines-when-you-quit/quit-medicines-are-safer-than-smoking/index.html',null,array['other'],array['release_tension','oral_sensory'],array['cigarette'],array['nrt'],array['nrt_gum','nrt_spray'],true,100,'2026-08-16'),
('vape_is_harmless','Вейп безвреден','Меньший риск относительно горящих сигарет в отдельных сценариях не означает отсутствие вреда или никотиновой зависимости','Никотиновые электронные сигареты имеют cessation evidence для cigarette smoking в регулируемых исследованиях, но это не доказательство безвредности и не то же самое, что прекращение никотина.','harm_reduction_confusion','A','Cessation vs harm distinction','Cochrane — Electronic cigarettes for smoking cessation','https://www.cochrane.org/evidence/CD010216_can-electronic-cigarettes-help-people-stop-smoking-and-do-they-have-any-unwanted-effects-when-used',null,array['other'],array['pleasure'],array['vape','cigarette'],array['vape','harm_reduction'],array[]::text[],true,110,'2026-08-16'),
('weight_is_inevitable','Если брошу, обязательно сильно поправлюсь','После отказа вес у части людей растёт, но разброс большой. Это отдельная управляемая задача, а не неизбежный одинаковый исход','Meta-analysis показывает средний post-cessation weight gain, но между людьми есть большой разброс, включая отсутствие набора и снижение веса.','weight_expectancy','A','Population weight-change evidence','BMJ — Weight gain in smokers after quitting cigarettes','https://www.bmj.com/content/345/bmj.e4439',null,array['other'],array['pleasure','oral_sensory'],array['cigarette'],array['weight'],array['walk_two_minutes','apple_crunch','carrot_crunch'],true,120,'2026-08-16'),
('too_late_to_quit','Я курю слишком давно — уже поздно','Раньше бросить лучше, но польза отказа сохраняется и после долгого стажа','Large cohort evidence показывает существенную разницу mortality между продолжающими курить и бросившими в разных возрастных периодах.','fatalism','A','Population mortality/cessation benefit; не индивидуальный прогноз','Jha et al. NEJM 2013','https://www.nejm.org/doi/full/10.1056/NEJMsa1211128','10.1056/NEJMsa1211128',array['other'],array['meaning'],array['cigarette'],array['fatalism'],array['meaning_read','future_resource'],true,130,'2026-08-16'),
('lapse_resets_all','Если закурил — всё пропало','Один эпизод не стирает предыдущую работу. Он показывает сильную Связку и даёт данные для следующего ответа','Relapse-prevention guidance рекомендует пересматривать coping strategy после неудачных попыток, а не превращать единичный эпизод в окончательный приговор.','abstinence_violation','B','Relapse-prevention guidance','NICE NG209 — Treating tobacco dependence','https://www.nice.org.uk/guidance/ng209/chapter/treating-tobacco-dependence',null,array['other'],array['meaning','release_tension'],array['cigarette','hookah','vape'],array['lapse'],array['meaning_read','write_real_need'],true,140,'2026-08-16'),
('can_quit_anytime','Я могу бросить когда захочу','Не нужно спорить с этим. Проще посмотреть на свои данные: какие эпизоды повторяются и насколько легко реально пропустить привычный ответ','ALIVE заменяет спор наблюдением за повторяемостью cue → urge → nicotine response.','control_belief','C','ALIVE behavioural hypothesis','ALIVE Method v1','https://github.com/wd7b3k/Alive/blob/main/docs/METHODOLOGY.md',null,array['spontaneous','other'],array['meaning'],array['cigarette','hookah','vape'],array['control'],array['write_real_need'],true,150,'2026-08-16'),
('too_stressed_to_quit','Сейчас слишком стрессовый период','Страх стать более напряжённым после отказа понятен, но прекращение курения не означает постоянный рост стресса','Stress-related expectancies themselves have been associated with lower odds of abstinence in prospective data; withdrawal support and evidence-based treatment can reduce the burden of a quit attempt.','stress_expectancy','B','Prospective expectancy evidence + withdrawal support','Stress-related expectations about smoking cessation','https://pubmed.ncbi.nlm.nih.gov/28367399/',null,array['tension','anxiety','uncertainty'],array['release_tension','pause'],array['cigarette'],array['stress'],array['five_long_exhales','nrt_gum','walk_two_minutes'],true,160,'2026-08-16'),
('one_of_few_pleasures','Курение — одна из моих немногих радостей','Не нужно отрицать удовольствие. Полезнее разобрать, что именно в нём ценно: никотин, пауза, ожидание, место, вкус или контакт','Positive smoking outcome expectancies связаны с lapse, а preliminary expectancy-challenge research показывает потенциал работы с альтернативными reinforcers.','positive_reinforcement','B','Outcome expectancy evidence; Myth Engine remains experimental','Kaufmann & Haaga 2023','https://pubmed.ncbi.nlm.nih.gov/36356395/','10.1016/j.addbeh.2022.107542',array['boredom','evening','social'],array['pleasure','pause','connection'],array['cigarette','hookah','vape'],array['pleasure','boredom'],array['favorite_song','tea_pause','savor_result'],true,170,'2026-08-16'),
('without_smoking_more_anxious','Без сигарет я навсегда стану тревожнее','Withdrawal может временно быть неприятным, но в долгосрочных данных прекращение курения не связано с ухудшением психического состояния и часто сопровождается улучшением','Важно различать первые withdrawal symptoms и более долгий период после cessation.','mental_health_expectancy','A','Systematic review evidence','Taylor et al. Cochrane 2021','https://pubmed.ncbi.nlm.nih.gov/33687070/','10.1002/14651858.CD013522.pub2',array['anxiety','irritability','tension'],array['release_tension'],array['cigarette'],array['mental_health'],array['ground_feet','five_long_exhales'],true,180,'2026-08-16')
on conflict (code) do update set
  title=excluded.title,short_reframe=excluded.short_reframe,explanation=excluded.explanation,
  mechanism=excluded.mechanism,evidence_level=excluded.evidence_level,evidence_scope=excluded.evidence_scope,
  source_title=excluded.source_title,source_url=excluded.source_url,doi=excluded.doi,
  trigger_codes=excluded.trigger_codes,need_codes=excluded.need_codes,product_types=excluded.product_types,
  context_tags=excluded.context_tags,replacement_codes=excluded.replacement_codes,published=true,
  sort_order=excluded.sort_order,last_verified_at=excluded.last_verified_at;
