-- ALIVE v3.1 Facts seed
insert into public.facts_catalog
(code,title,short_text,full_text,category,benefit,evidence_level,evidence_kind,source_title,source_url,doi,sample_size,product_types,min_pack_years,context_tags,published,sort_order,last_verified_at)
values
('low_intensity_cvd','Даже одна сигарета — не «почти ноль»','Для сердечно-сосудистого риска уменьшение количества сигарет не работает как простая линейная шкала','Meta-analysis 141 cohort studies показал, что примерно одна сигарета в день несёт непропорционально большую долю excess coronary heart disease/stroke risk относительно 20 сигарет в день. Это population evidence, а не личный прогноз.','heart',false,'A','meta_analysis','Hackshaw et al. BMJ 2018','https://www.bmj.com/content/360/bmj.j5855',null,null,array['cigarette'],null,array['risk','low_intensity'],true,10,'2026-08-16'),
('mortality_decade','Продолжение курения связано с потерей примерно десятилетия жизни','В крупной американской когорте current smokers в среднем теряли более 10 лет жизни по сравнению с never smokers','Это population average из большой cohort study и не предсказывает срок жизни конкретного человека.','mortality',false,'A','prospective_cohort','Jha et al. NEJM 2013','https://www.nejm.org/doi/full/10.1056/NEJMsa1211128','10.1056/NEJMsa1211128',216917,array['cigarette'],null,array['risk'],true,20,'2026-08-16'),
('quit_before_40','Отказ раньше даёт особенно большой выигрыш','В той же крупной когорте отказ до 40 лет устранял большую часть excess mortality, связанной с продолжением курения','Раньше лучше, но это не означает, что после 40 бросать бессмысленно.','mortality',true,'A','prospective_cohort','Jha et al. NEJM 2013','https://www.nejm.org/doi/full/10.1056/NEJMsa1211128','10.1056/NEJMsa1211128',216917,array['cigarette'],null,array['benefit'],true,30,'2026-08-16'),
('heavy_smoker_cvd_5y','Сердечно-сосудистый риск начинает меняться после отказа','У former heavy smokers в JAMA cohort risk cardiovascular disease был ниже уже в первые 5 лет после cessation по сравнению с current smokers','Study included 8 770 participants and defined heavy smoking as at least 20 pack-years. Risk относительно never smokers мог оставаться повышенным существенно дольше.','heart',true,'A','prospective_cohort','Duncan et al. JAMA 2019','https://jamanetwork.com/journals/jama/fullarticle/2748507','10.1001/jama.2019.10298',8770,array['cigarette'],20,array['benefit','heavy_smoking'],true,40,'2026-08-16'),
('mental_health_after_quit','Отказ не означает постоянное ухудшение настроения','Cochrane review не нашёл evidence долгосрочного ухудшения mental health после cessation; по ряду outcomes состояние у бросивших было лучше','Первые недели withdrawal и долгосрочное mental health — не одно и то же.','mental_health',true,'A','systematic_review','Taylor et al. Cochrane 2021','https://pubmed.ncbi.nlm.nih.gov/33687070/','10.1002/14651858.CD013522.pub2',null,array['cigarette'],null,array['benefit','stress'],true,50,'2026-08-16'),
('nrt_safer','НЗТ намного безопаснее продолжения курения','НЗТ даёт никотин без сигаретного дыма и токсичных продуктов горения','Никотин не становится полезным веществом, но тяжёлый вред combustible cigarettes нельзя приравнивать к НЗТ.','treatment',true,'A','guideline_public_health','CDC — Quit Medicines Are Much Safer Than Smoking','https://www.cdc.gov/tobacco/campaign/tips/quit-smoking/quit-smoking-medications/3-reasons-to-use-medicines-when-you-quit/quit-medicines-are-safer-than-smoking/index.html',null,null,array['cigarette'],null,array['nrt','benefit'],true,60,'2026-08-16'),
('light_not_safe','Light не делает сигарету безопасной','Low-tar/light descriptors не означают существенно меньший риск для здоровья','Исторические machine yields и descriptors могут создавать ложную интуицию безопасности.','product',false,'A','surgeon_general','U.S. Surgeon General 2000 highlights','https://archive.cdc.gov/www_cdc_gov/tobacco/sgr/2000/highlights.html',null,null,array['cigarette'],null,array['risk','product'],true,70,'2026-08-16'),
('hookah_not_safe','Кальян не становится безопасным из-за воды','Вода в кальяне не отфильтровывает дым до безопасного уровня','CDC указывает, что hookah smoke содержит многие из тех же вредных компонентов, что и cigarette smoke, а уголь добавляет carbon monoxide и другие токсиканты.','product',false,'A','public_health','CDC — Hookahs','https://www.cdc.gov/tobacco/other-tobacco-products/hookahs.html',null,null,array['hookah'],null,array['hookah','risk'],true,75,'2026-08-16'),
('secondhand_no_safe','Для пассивного табачного дыма нет безопасного уровня воздействия','Secondhand smoke вызывает серьёзные cardiovascular и respiratory последствия','Эта карточка особенно важна, когда курение происходит рядом с другими людьми, но ALIVE не использует её для shame.','others',false,'A','public_health','CDC — About Secondhand Smoke','https://www.cdc.gov/tobacco/secondhand-smoke/about.html',null,null,array['cigarette','hookah'],null,array['others','social'],true,80,'2026-08-16'),
('oral_health','Табак влияет не только на лёгкие','Курение связано с заболеваниями дёсен, потерей зубов и раком полости рта','Внешний вид — только небольшая часть oral-health последствий.','oral_health',false,'A','public_health','CDC — Tobacco Use and Oral Health Facts','https://www.cdc.gov/oral-health/data-research/facts-stats/fast-facts-tobacco-use-and-oral-health.html',null,null,array['cigarette'],null,array['oral','risk'],true,90,'2026-08-16'),
('rewards_work','Награды могут реально помогать бросить','Cochrane 2025 нашёл high-certainty evidence, что incentives повышают long-term quit rates','В основном long-term анализе 39 исследований и 18 303 участника: pooled RR 1.52. Это основание для добровольного Freedom Fund, а не для азартной механики.','behavior',true,'A','systematic_review','Notley et al. Cochrane 2025','https://www.cochrane.org/evidence/CD004307_can-rewards-help-people-quit-smoking-and-do-they-work-long-term','10.1002/14651858.CD004307.pub7',18303,array['cigarette'],null,array['reward','benefit'],true,100,'2026-08-16'),
('treatment_plus_support','Поддержка и лекарства работают сильнее вместе','WHO рекомендует сочетать доказательную фармакотерапию с поведенческой поддержкой','ALIVE может быть частью digital support, но не заменяет врача или доказательную cessation care.','treatment',true,'A','guideline','WHO Clinical Treatment Guideline 2024','https://www.who.int/publications/i/item/9789240096431',null,null,array['cigarette','hookah'],null,array['treatment','benefit'],true,110,'2026-08-16'),
('who_medications','Есть несколько доказательных медикаментозных вариантов','WHO рекомендует NRT, varenicline, bupropion и cytisine для tobacco cessation','Выбор конкретного препарата и безопасность зависят от человека и инструкции/медицинской консультации.','treatment',true,'A','guideline','WHO Clinical Treatment Guideline 2024','https://www.who.int/publications/i/item/9789240096431',null,null,array['cigarette','hookah'],null,array['treatment'],true,120,'2026-08-16'),
('cues_matter','Окружение может быть сильнее абстрактной силы воли','EMA meta-analysis нашёл сильную within-person связь environmental/social cues с lapse','Поэтому изменение места, последовательности и доступности продукта — не мелочь, а осмысленная behavioural target.','behavior',true,'B','systematic_review_meta_analysis','Perski et al. Addiction 2023','https://pubmed.ncbi.nlm.nih.gov/36807443/','10.1111/add.16173',null,array['cigarette'],null,array['cues','behavior'],true,130,'2026-08-16'),
('craving_is_signal','Тяга — изменяющееся состояние, а не приказ','В EMA studies momentary craving связан с lapse, но сам факт тяги не означает неизбежное курение','ALIVE использует этот момент как точку вмешательства: заметить контекст и попробовать другой ответ.','behavior',true,'B','systematic_review_meta_analysis','Perski et al. Addiction 2023','https://pubmed.ncbi.nlm.nih.gov/36807443/','10.1111/add.16173',null,array['cigarette'],null,array['craving','behavior'],true,140,'2026-08-16'),
('expectancies_predict_lapse','Обещание сигареты — часть зависимости','Positive smoking outcome expectancies в EMA research предсказывали first lapse на следующий день','Это одна из причин, почему ALIVE отдельно работает с Мифами и сравнивает ожидание с реальным outcome.','behavior',true,'B','ecological_momentary_assessment','Gwaltney et al. 2005','https://pubmed.ncbi.nlm.nih.gov/16351387/','10.1037/0021-843X.114.4.661',305,array['cigarette'],null,array['myths','behavior'],true,150,'2026-08-16'),
('digital_support','Цифровая поддержка может быть частью отказа','WHO допускает text messaging, smartphone apps и internet programmes как adjunct или self-management tools','Это не означает, что любое приложение автоматически эффективно: конкретный продукт должен доказать собственную ценность.','behavior',true,'A','guideline','WHO Clinical Treatment Guideline 2024','https://www.who.int/publications/i/item/9789240096431',null,null,array['cigarette','hookah'],null,array['digital','benefit'],true,160,'2026-08-16'),
('weight_varies','Набор веса после отказа не одинаков у всех','Средний post-cessation gain существует, но individual variation очень большая','Вес можно рассматривать как отдельную задачу питания и движения, не как аргумент продолжать inhaled tobacco smoke.','weight',true,'A','meta_analysis','BMJ — Weight gain in smokers after quitting cigarettes','https://www.bmj.com/content/345/bmj.e4439',null,null,array['cigarette'],null,array['weight'],true,170,'2026-08-16'),
('lapse_is_data','Один эпизод не обязан становиться возвратом к старому режиму','После эпизода полезнее разобрать trigger, need и следующий coping response, чем объявлять попытку законченной','ALIVE сознательно не использует «день ноль» как наказание и сохраняет предыдущие данные.','behavior',true,'B','guideline','NICE NG209 — Treating tobacco dependence','https://www.nice.org.uk/guidance/ng209/chapter/treating-tobacco-dependence',null,null,array['cigarette','hookah','vape'],null,array['lapse','benefit'],true,180,'2026-08-16')
on conflict (code) do update set
  title=excluded.title,short_text=excluded.short_text,full_text=excluded.full_text,category=excluded.category,
  benefit=excluded.benefit,evidence_level=excluded.evidence_level,evidence_kind=excluded.evidence_kind,
  source_title=excluded.source_title,source_url=excluded.source_url,doi=excluded.doi,sample_size=excluded.sample_size,
  product_types=excluded.product_types,min_pack_years=excluded.min_pack_years,context_tags=excluded.context_tags,
  published=true,sort_order=excluded.sort_order,last_verified_at=excluded.last_verified_at;
