-- ALIVE v3.1 behavioural content seed
-- All user-facing content is Russian. Medical statements are source-linked and editorially reviewable.

-- Backfill mechanism metadata for the existing v3.0 replacement catalog.
update public.replacements_catalog
set mechanism = coalesce(mechanism,
  case category
    when 'breath' then 'breathing'
    when 'movement' then 'movement'
    when 'drink' then 'drink'
    when 'food' then 'food'
    when 'nrt' then 'evidence_treatment'
    when 'meaning' then 'meaning'
    when 'orienting' then 'attention'
    when 'observation' then 'attention'
    when 'journal' then 'reflection'
    when 'contact' then 'social'
    when 'environment' then 'context_change'
    when 'music' then 'sensory'
    when 'rest' then 'pause'
    when 'reward' then 'reward'
    else 'ritual'
  end),
  evidence_level = coalesce(evidence_level,
    case when category = 'nrt' then 'A'
         when category in ('movement','breath') then 'B'
         else 'C' end),
  evidence_scope = coalesce(evidence_scope,
    case when category = 'nrt' then 'Доказательный инструмент прекращения курения; ALIVE не назначает дозировки'
         when category = 'movement' then 'Есть данные по кратковременному снижению тяги; не самостоятельная гарантия отказа'
         when category = 'breath' then 'Поддержка состояния и возбуждения; long-term smoking cessation outcome не установлен'
         else 'Поведенческая эвристика ALIVE; эффективность проверяется по личным outcomes' end),
  eligibility = coalesce(eligibility,'{}'::jsonb) || jsonb_build_object(
    'mechanism', coalesce(mechanism,
      case category
        when 'breath' then 'breathing' when 'movement' then 'movement' when 'drink' then 'drink'
        when 'food' then 'food' when 'nrt' then 'evidence_treatment' when 'meaning' then 'meaning'
        when 'orienting' then 'attention' when 'observation' then 'attention' when 'journal' then 'reflection'
        when 'contact' then 'social' when 'environment' then 'context_change' when 'music' then 'sensory'
        when 'rest' then 'pause' when 'reward' then 'reward' else 'ritual' end),
    'evidence_level', coalesce(evidence_level,
      case when category='nrt' then 'A' when category in ('movement','breath') then 'B' else 'C' end)
  );

-- Evidence anchors for existing high-value items.
update public.replacements_catalog
set source_title='WHO Clinical Treatment Guideline for Tobacco Cessation in Adults 2024',
    source_url='https://www.who.int/publications/i/item/9789240096431',
    evidence_level='A', mechanism='evidence_treatment',
    eligibility=coalesce(eligibility,'{}'::jsonb) || '{"mechanism":"evidence_treatment","evidence_level":"A"}'::jsonb
where code in ('nrt_spray','nrt_gum');

update public.replacements_catalog
set source_title='Physical activity and acute cigarette craving evidence',
    source_url='https://pubmed.ncbi.nlm.nih.gov/22585034/',
    evidence_level='B', mechanism='movement',
    eligibility=coalesce(eligibility,'{}'::jsonb) || '{"mechanism":"movement","evidence_level":"B"}'::jsonb
where category='movement';

update public.replacements_catalog
set source_title='Brief structured respiration practices and mood/arousal',
    source_url='https://pubmed.ncbi.nlm.nih.gov/36630953/',
    evidence_level='B', mechanism='breathing',
    eligibility=coalesce(eligibility,'{}'::jsonb) || '{"mechanism":"breathing","evidence_level":"B"}'::jsonb
where category='breath';

insert into public.replacements_catalog
(code,title,instruction,category,need_codes,product_types,eligibility,published,sort_order,icon,duration,summary,safety,mechanism,evidence_level,evidence_scope,source_title,source_url,context_tags,rotation_weight,intensity_min,intensity_max)
values
('ground_feet','Стопы в пол','Поставь обе стопы на пол и слегка прижми их к поверхности на 5 секунд. Отпусти и заметь вес тела. Повтори 3 раза.','grounding',array['release_tension','pause','switch','self_presence'],array['cigarette','hookah','vape'],'{"mechanism":"grounding","evidence_level":"C"}',true,201,'ground','40 сек','Вернуть внимание из автоматизма в ощущение опоры','Без боли и без задержки дыхания','grounding','C','Короткая self-regulation эвристика ALIVE, адаптированная из HumanOS',null,null,array['stress','anxiety','overload'],1.1,1,10),
('press_release','Надавить и отпустить','Ладони на бёдра или стопы в пол. Надави уверенно на 5 секунд и полностью отпусти. Сделай 4 повтора.','grounding',array['release_tension','switch','self_presence'],array['cigarette','hookah','vape'],'{"mechanism":"grounding","evidence_level":"C"}',true,202,'hands','45 сек','Коротко собрать границы тела и отпустить напряжение','Без боли; дыши обычно','grounding','C','Self-regulation эвристика ALIVE, адаптированная из HumanOS',null,null,array['stress','anger','anxiety'],1.0,1,10),
('five_long_exhales','Пять спокойных выдохов','Сделай обычный вдох и чуть более длинный мягкий выдох. Повтори пять раз, не стараясь дышать глубже обычного.','breath',array['release_tension','pause','switch'],array['cigarette','hookah','vape'],'{"mechanism":"breathing","evidence_level":"B"}',true,203,'breath','1 мин','Снизить внутреннее ускорение без сложной техники','Если кружится голова или неприятно — сразу вернись к обычному дыханию','breathing','B','Evidence относится к состоянию/arousal, а не к гарантии прекращения курения','Brief structured respiration practices and mood/arousal','https://pubmed.ncbi.nlm.nih.gov/36630953/',array['stress','anxiety'],1.2,1,10),
('attention_321','Три — два — один','Назови про себя 3 вещи, которые видишь, 2 звука вокруг и 1 ощущение в теле.','orienting',array['switch','release_tension','self_presence'],array['cigarette','hookah','vape'],'{"mechanism":"attention","evidence_level":"C"}',true,204,'eye','45 сек','Вернуть фокус в то, что происходит прямо сейчас','Не задерживайся на неприятном ощущении','attention','C','Attention-reset эвристика ALIVE, адаптированная из HumanOS',null,null,array['stress','thinking','phone'],1.1,1,10),
('focus_point','Одна спокойная точка','Выбери один неподвижный предмет и смотри на него 30–45 секунд. Заметь форму, свет и края, ничего не анализируя.','orienting',array['switch','pause','self_presence'],array['cigarette','hookah','vape'],'{"mechanism":"attention","evidence_level":"C"}',true,205,'eye','45 сек','Сузить входящий шум до одной простой задачи',null,'attention','C','Attention-reset эвристика ALIVE, адаптированная из HumanOS',null,null,array['overload','work','phone'],0.95,1,10),
('listen_three_sounds','Три звука вокруг','Остановись на полминуты и найди три разных звука: близкий, средний и дальний.','orienting',array['switch','pause','self_presence'],array['cigarette','hookah','vape'],'{"mechanism":"attention","evidence_level":"C"}',true,206,'eye','40 сек','Переключить внимание с тяги на окружающую среду',null,'attention','C','Поведенческая эвристика ALIVE',null,null,array['spontaneous','boredom','stress'],0.9,1,10),
('shoulder_release','Плечи и челюсть','Опусти плечи, разожми зубы и на несколько секунд отпусти язык от нёба. Сделай обычный спокойный выдох.','grounding',array['release_tension','pause'],array['cigarette','hookah','vape'],'{"mechanism":"grounding","evidence_level":"C"}',true,207,'calm','40 сек','Убрать часть незаметного мышечного напряжения','Не тянуть шею через боль','grounding','C','Self-regulation эвристика ALIVE',null,null,array['work','driving','stress'],1.0,1,10),
('walk_two_minutes','Две минуты пройтись','Встань и две минуты просто походи — по комнате, коридору или улице. Не тренировка, а смена состояния.','movement',array['switch','stimulation','release_tension','pause'],array['cigarette','hookah','vape'],'{"mechanism":"movement","evidence_level":"B"}',true,208,'walk','2 мин','Сменить контекст и дать телу короткое движение','Выбирай только привычную и безопасную нагрузку','movement','B','Есть smoking-specific evidence для кратковременного уменьшения craving','Physical activity and acute cigarette craving evidence','https://pubmed.ncbi.nlm.nih.gov/22585034/',array['work','boredom','stress','after_meal'],1.25,1,10),
('stairs_one_flight','Один пролёт','Если лестница тебе подходит, спокойно пройди один пролёт вверх и обратно.','movement',array['stimulation','switch'],array['cigarette','hookah','vape'],'{"mechanism":"movement","evidence_level":"B"}',true,209,'walk','2 мин','Коротко включить тело и сменить ритм','Пропусти при боли, одышке, головокружении или если нагрузка тебе не привычна','movement','B','Acute activity может снижать craving; конкретная дозировка ALIVE экспериментальна','Physical activity and acute cigarette craving evidence','https://pubmed.ncbi.nlm.nih.gov/22585034/',array['low_energy','work'],0.7,1,7),
('sparkling_water','Газированная вода','Сделай несколько маленьких глотков прохладной газированной воды и сосредоточься на ощущениях во рту.','drink',array['oral_sensory','switch','pleasure','pause'],array['cigarette','hookah','vape'],'{"mechanism":"drink","evidence_level":"C"}',true,210,'tea','1 мин','Яркий сенсорный ритуал без дыма',null,'drink','C','Поведенческая эвристика ALIVE',null,null,array['oral','after_meal','coffee'],0.9,1,10),
('gum_sugarfree','Жвачка без сахара','Возьми жвачку без сахара и на минуту направь внимание на вкус и работу челюсти.','oral',array['oral_sensory','switch'],array['cigarette','hookah','vape'],'{"mechanism":"oral","evidence_level":"C"}',true,211,'leaf','2 мин','Занять рот без сигареты','Не использовать, если жевание вызывает боль или не подходит по здоровью','oral','C','Поведенческая эвристика ALIVE',null,null,array['driving','after_meal','coffee'],1.1,1,10),
('mint_reset','Мята','Возьми обычную мятную пастилку без никотина или освежи рот привычным безопасным способом.','oral',array['oral_sensory','switch','closure'],array['cigarette','hookah','vape'],'{"mechanism":"oral","evidence_level":"C"}',true,212,'leaf','1 мин','Сменить вкус и завершить старый ритуал',null,'oral','C','Поведенческая эвристика ALIVE',null,null,array['after_meal','coffee'],0.9,1,10),
('brush_teeth','Почистить зубы','После еды или кофе почисти зубы как новый знак: ритуал завершён.','ritual',array['closure','oral_sensory','switch'],array['cigarette','hookah','vape'],'{"mechanism":"context_change","evidence_level":"C"}',true,213,'finish','2 мин','Заменить привычную точку «еда → сигарета» другой точкой','Следуй обычным правилам ухода за зубами','context_change','C','Cue-restructuring эвристика ALIVE',null,null,array['after_meal','coffee'],1.15,1,10),
('hands_pen','Занять руки','Возьми ручку или небольшой безопасный предмет и минуту крути, рисуй линии или делай простые пометки.','manual',array['oral_sensory','switch','pause'],array['cigarette','hookah','vape'],'{"mechanism":"manual","evidence_level":"C"}',true,214,'hands','1 мин','Убрать часть привычки «что-то держать в руке»','Не использовать острые или опасные предметы','manual','C','Поведенческая эвристика ALIVE',null,null,array['work','phone','boredom'],0.95,1,10),
('apple_crunch','Яблоко','Если ты действительно голоден, съешь небольшое яблоко и не торопись.','food',array['oral_sensory','pleasure','stimulation'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,220,'leaf','3 мин','Хрустящий вариант, когда тяга совпала с голодом',null,'food','C','Пищевая эвристика ALIVE; не использовать как автоматический ответ на каждую тягу',null,null,array['hunger','oral'],0.8,1,10),
('pear_crunch','Груша','Если голод есть, выбери небольшую грушу как одну порцию, а не как обязательное «заедание» тяги.','food',array['oral_sensory','pleasure'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,221,'leaf','3 мин','Сочный хрустящий вариант при реальном голоде',null,'food','C','Пищевая эвристика ALIVE',null,null,array['hunger','oral'],0.75,1,10),
('carrot_crunch','Морковь','Если хочется именно пожевать и ты голоден, возьми небольшую порцию моркови.','food',array['oral_sensory','stimulation'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,222,'leaf','3 мин','Хрустящая несладкая альтернатива',null,'food','C','Пищевая эвристика ALIVE',null,null,array['hunger','oral'],0.85,1,10),
('cucumber_crunch','Огурец','Небольшая порция свежего огурца, если тяга совпала с голодом или хочется хрустящего вкуса.','food',array['oral_sensory','pleasure'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,223,'leaf','3 мин','Лёгкая хрустящая альтернатива',null,'food','C','Пищевая эвристика ALIVE',null,null,array['hunger','oral'],0.8,1,10),
('sweet_pepper_crunch','Сладкий перец','Если голод есть, съешь небольшую порцию сладкого перца и обрати внимание на вкус и хруст.','food',array['oral_sensory','pleasure'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,224,'leaf','3 мин','Яркий несигаретный вкус при реальном голоде',null,'food','C','Пищевая эвристика ALIVE',null,null,array['hunger','oral'],0.8,1,10),
('berries_portion','Небольшая порция ягод','Если ты голоден, выбери небольшую порцию ягод и ешь без телефона.','food',array['pleasure','oral_sensory'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,225,'leaf','3 мин','Яркий вкус без автоматического перекуса',null,'food','C','Пищевая эвристика ALIVE',null,null,array['hunger','oral'],0.7,1,10),
('plain_yogurt','Натуральный йогурт','Если есть голод, выбери небольшую порцию натурального йогурта.','food',array['pleasure','oral_sensory'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,226,'leaf','4 мин','Более насыщающий вариант при реальном голоде','Учитывай личную переносимость молочных продуктов','food','C','Пищевая эвристика ALIVE',null,null,array['hunger'],0.7,1,10),
('cottage_cheese','Творог','Если тяга совпала с голодом, выбери небольшую привычную порцию творога.','food',array['pleasure','oral_sensory'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,227,'leaf','4 мин','Сытный вариант вместо случайного сладкого перекуса','Учитывай личную переносимость молочных продуктов','food','C','Пищевая эвристика ALIVE',null,null,array['hunger'],0.65,1,10),
('egg_portion','Яйцо','Если сейчас именно голод, а не только тяга, выбери одно привычно приготовленное яйцо.','food',array['stimulation','oral_sensory'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,228,'leaf','5 мин','Небольшая белковая еда при реальном голоде','Не использовать при индивидуальных ограничениях','food','C','Пищевая эвристика ALIVE',null,null,array['hunger'],0.6,1,10),
('nuts_small','Небольшая порция орехов','Если голоден, возьми небольшую заранее отмеренную порцию орехов и убери упаковку.','food',array['oral_sensory','pleasure'],array['cigarette','hookah','vape'],'{"mechanism":"food","evidence_level":"C","use_when_hungry":true}',true,229,'leaf','3 мин','Плотный вариант при голоде без бесконечного перекуса','Не использовать при аллергии; учитывать индивидуальные ограничения','food','C','Пищевая эвристика ALIVE',null,null,array['hunger'],0.6,1,10),
('phone_down_pause','Две минуты без экрана','Положи телефон экраном вниз и две минуты ничего не листай. Можно просто смотреть в окно или сидеть.','pause',array['pause','self_presence','release_tension','switch'],array['cigarette','hookah','vape'],'{"mechanism":"pause","evidence_level":"C"}',true,230,'pause','2 мин','Вернуть себе настоящую паузу вместо связки «телефон + никотин»',null,'pause','C','Поведенческая эвристика ALIVE',null,null,array['phone','work','evening'],1.1,1,10),
('gaze_far_minute','Минута смотреть вдаль','Посмотри в окно или на дальний объект около минуты. Ничего не решай в это время.','orienting',array['pause','switch','self_presence'],array['cigarette','hookah','vape'],'{"mechanism":"attention","evidence_level":"C"}',true,231,'eye','1 мин','Сменить зрительный фокус и дать мозгу короткую паузу',null,'attention','C','Поведенческая эвристика ALIVE',null,null,array['work','phone','overload'],0.95,1,10),
('write_real_need','Одна строка о том, что нужно','Напиши одну строку: «Сейчас я хочу от сигареты…» и закончи фразу без анализа.','journal',array['meaning','release_tension','pause','switch','closure'],array['cigarette','hookah','vape'],'{"mechanism":"reflection","evidence_level":"C"}',true,232,'journal','1 мин','Отделить функцию от привычной формы ритуала',null,'reflection','C','Поведенческая эвристика ALIVE',null,null,array['stress','thinking','spontaneous'],1.0,1,10),
('focus_two_minutes','Две минуты одного дела','Выбери самый маленький следующий шаг и делай только его две минуты: открыть файл, написать первую строку, убрать один предмет.','focus',array['stimulation','switch','closure'],array['cigarette','hookah','vape'],'{"mechanism":"focus","evidence_level":"C"}',true,233,'focus','2 мин','Проверить, нужна ли сигарета или нужен был короткий старт',null,'focus','C','Поведенческая эвристика ALIVE',null,null,array['task_start','work','procrastination'],1.05,1,9),
('text_support','Одно сообщение человеку','Напиши человеку, которому доверяешь: «Сейчас сильная тяга, просто побудь со мной пару минут».','contact',array['connection','release_tension'],array['cigarette','hookah','vape'],'{"mechanism":"social","evidence_level":"C"}',true,234,'people','2 мин','Получить контакт напрямую, а не через общий ритуал курения','Только если это комфортный и заранее выбранный контакт','social','C','Поведенческая эвристика ALIVE',null,null,array['social','stress'],0.8,1,10)
on conflict (code) do update set
  title=excluded.title,instruction=excluded.instruction,category=excluded.category,need_codes=excluded.need_codes,
  product_types=excluded.product_types,eligibility=excluded.eligibility,published=true,sort_order=excluded.sort_order,
  icon=excluded.icon,duration=excluded.duration,summary=excluded.summary,safety=excluded.safety,
  mechanism=excluded.mechanism,evidence_level=excluded.evidence_level,evidence_scope=excluded.evidence_scope,
  source_title=excluded.source_title,source_url=excluded.source_url,context_tags=excluded.context_tags,
  rotation_weight=excluded.rotation_weight,intensity_min=excluded.intensity_min,intensity_max=excluded.intensity_max;

-- Myths / smoking outcome expectancies.
insert into public.myths_catalog
(code,title,short_reframe,explanation,mechanism,evidence_level,evidence_scope,source_title,source_url,doi,trigger_codes,need_codes,product_types,context_tags,replacement_codes,published,sort_order,last_verified_at)
values
('calms_me','Сигарета меня успокаивает','Облегчение может быть реальным, но часть напряжения возникает из-за самой никотиновой зависимости между сигаретами','Никотиновый withdrawal может давать раздражительность, тревогу и внутреннее беспокойство. Следующая доза временно снимает часть этого состояния, поэтому цикл легко принять за лечение стресса.','negative_reinforcement','B','Withdrawal mechanism + mental-health cessation evidence','CDC — 7 Common Withdrawal Symptoms','https://www.cdc.gov/tobacco/campaign/tips/quit-smoking/7-common-withdrawal-symptoms/index.html',null,array['tension','anger','irritability','anxiety','uncertainty'],array['release_tension','pause'],array['cigarette','vape'],array['stress','anxiety'],array['five_long_exhales','ground_feet','walk_two_minutes'],true,10,'2026-08-16'),
('focus_better','С сигаретой я лучше соображаю','Никотин может временно снять withdrawal-related трудности с концентрацией. Это не делает зависимость хорошим способом поддерживать фокус','Проблемы концентрации являются известным симптомом nicotine withdrawal. Полезно отделить снятие withdrawal от устойчивой способности сосредоточиться.','withdrawal_reversal','B','Withdrawal/concentration mechanism','CDC — 7 Common Withdrawal Symptoms','https://www.cdc.gov/tobacco/campaign/tips/quit-smoking/7-common-withdrawal-symptoms/index.html',null,array['work_computer','task_start','thinking'],array['stimulation','switch'],array['cigarette','vape'],array['focus','work'],array['focus_two_minutes','walk_two_minutes','water'],true,20,'2026-08-16'),
('only_real_pause','Сигарета — мой единственный настоящий отдых','Пауза тебе действительно нужна. Дым — не обязательная её часть','Курение часто объединяет разрешение остановиться, смену места, дыхательный ритм и никотин в один пакет. ALIVE сохраняет функцию паузы и меняет форму.','ritual_bundle','C','Behavioural decomposition hypothesis','ALIVE Method v1','https://github.com/wd7b3k/Alive/blob/main/docs/METHODOLOGY.md',null,array['task_transition','after_task','evening'],array['pause','solitude','self_presence'],array['cigarette','hookah','vape'],array['pause'],array['phone_down_pause','tea_pause','gaze_far_minute'],true,30,'2026-08-16'),
('coffee_needs_smoke','Кофе без сигареты уже не тот','Повторяемая пара «кофе → сигарета» может стать сильным cue. Сам кофе не требует продолжения этой цепочки','Environmental cues являются важными непосредственными antecedents lapse. Изменение места, последовательности или следующего действия помогает тестировать новую связку.','cue_association','B','EMA antecedent evidence; конкретная ALIVE замена экспериментальна','Perski et al. Addiction 2023','https://pubmed.ncbi.nlm.nih.gov/36807443/','10.1111/add.16173',array['coffee'],array['pleasure','closure','pause'],array['cigarette','vape'],array['coffee'],array['brush_teeth','tea_ritual','walk_two_minutes'],true,40,'2026-08-16'),
('meal_needs_smoke','После еды без сигареты будто не закончено','Ощущение завершения можно сохранить другим последним действием','Repeated cue pairing может сделать сигарету привычной точкой завершения еды. Новый terminal action позволяет разорвать последовательность без запрета на саму паузу.','cue_association','C','Cue-restructuring ALIVE hypothesis','ALIVE Method v1','https://github.com/wd7b3k/Alive/blob/main/docs/METHODOLOGY.md',null,array['after_meal'],array['closure','oral_sensory'],array['cigarette','vape'],array['after_meal'],array['brush_teeth','mint_reset','walk_two_minutes'],true,50,'2026-08-16'),
('smoking_is_style','Курить стильно','Рекламный образ легко отделить от дыма, запаха и реальных последствий для полости рта','ALIVE не спорит со вкусом и не стыдит человека. Мы только возвращаем в образ те физические эффекты курения, которые эстетическая романтизация обычно убирает из кадра.','identity_expectancy','C','Identity reframe + factual health support','CDC — Smoking, Gum Disease, and Tooth Loss','https://www.cdc.gov/tobacco/about/cigarettes-and-cardiovascular-disease.html',null,array['social','hookah_venue'],array['pleasure','connection','meaning'],array['cigarette','hookah','vape'],array['identity','social'],array['meaning_read','meaning_card'],true,60,'2026-08-16'),
('social_helper','Курение помогает мне общаться','Общий выход и контакт могут быть приятны сами по себе. Сигарета не обязана быть пропуском в разговор','Социальные cues тесно связаны с lapse, но функция общения может быть закрыта напрямую.','social_cue','B','Environmental/social cue evidence','Perski et al. Addiction 2023','https://pubmed.ncbi.nlm.nih.gov/36807443/','10.1111/add.16173',array['social','hookah_venue'],array['connection'],array['cigarette','hookah','vape'],array['social'],array['text_support','stay_close'],true,70,'2026-08-16'),
('one_does_not_count','Одна сигарета почти не считается','Для сердца и сосудов риск не уменьшается линейно вместе с количеством сигарет','Большой meta-analysis cohort studies показал непропорционально высокий cardiovascular excess risk даже при примерно одной сигарете в день.','risk_minimization','A','Population cardiovascular risk; не индивидуальный прогноз','Hackshaw et al. BMJ 2018','https://www.bmj.com/content/360/bmj.j5855',null,array['spontaneous'],array['pleasure'],array['cigarette'],array['risk'],array['meaning_read'],true,80,'2026-08-16'),
('light_is_safer','Light безопаснее обычных сигарет','Маркировка light или low-tar не превращает сигарету в безопасную альтернативу','Низкие machine-measured tar/nicotine yields и маркетинговые descriptors исторически создавали ложное ощущение существенно меньшего риска.','risk_minimization','A','Authoritative tobacco-harm evidence','U.S. Surgeon General 2000 highlights','https://archive.cdc.gov/www_cdc_gov/tobacco/sgr/2000/highlights.html',null,array['other'],array['pleasure'],array['cigarette'],array['risk','product'],array[],true,90,'2026-08-16'),
('nrt_same_as_smoking','НЗТ — почти то же самое, что курить','Никотин остаётся никотином, но сигаретный дым добавляет токсичные продукты горения. НЗТ намного безопаснее продолжения курения','NRT доставляет nicotine без сигаретного combustion smoke и используется как доказательная помощь при отказе.','treatment_misconception','A','Cessation medication safety','CDC — Quit Medicines Are Much Safer Than Smoking','https://www.cdc.gov/tobacco/campaign/tips/quit-smoking/quit-smoking-medications/3-reasons-to-use-medicines-when-you-quit/quit-medicines-are-safer-than-smoking/index.html',null,array['other'],array['release_tension','oral_sensory'],array['cigarette'],array['nrt'],array['nrt_gum','nrt_spray'],true,100,'2026-08-16'),
('vape_is_harmless','Вейп безвреден','Меньший риск относительно горящих сигарет в отдельных сценариях не означает отсутствие вреда или никотиновой зависимости','Никотиновые электронные сигареты имеют cessation evidence для cigarette smoking в регулируемых исследованиях, но это не доказательство безвредности и не то же самое, что прекращение никотина.','harm_reduction_confusion','A','Cessation vs harm distinction','Cochrane — Electronic cigarettes for smoking cessation','https://www.cochrane.org/evidence/CD010216_electronic-cigarettes-smoking-cessation',null,array['other'],array['pleasure'],array['vape','cigarette'],array['vape','harm_reduction'],array[],true,110,'2026-08-16'),
('weight_is_inevitable','Если брошу, обязательно сильно поправлюсь','После отказа вес у части людей растёт, но разброс большой. Это отдельная управляемая задача, а не неизбежный одинаковый исход','Meta-analysis показывает средний post-cessation weight gain, но между людьми есть большой разброс, включая отсутствие набора и снижение веса.','weight_expectancy','A','Population weight-change evidence','BMJ — Weight gain in smokers after quitting cigarettes','https://www.bmj.com/content/345/bmj.e4439',null,array['other'],array['pleasure','oral_sensory'],array['cigarette'],array['weight'],array['walk_two_minutes','apple_crunch','carrot_crunch'],true,120,'2026-08-16'),
('too_late_to_quit','Я курю слишком давно — уже поздно','Раньше бросить лучше, но польза отказа сохраняется и после долгого стажа','Large cohort evidence показывает существенную разницу mortality между продолжающими курить и бросившими в разных возрастных периодах.','fatalism','A','Population mortality/cessation benefit; не индивидуальный прогноз','Jha et al. NEJM 2013','https://www.nejm.org/doi/full/10.1056/NEJMsa1211128','10.1056/NEJMsa1211128',array['other'],array['meaning'],array['cigarette'],array['fatalism'],array['meaning_read','future_resource'],true,130,'2026-08-16'),
('lapse_resets_all','Если закурил — всё пропало','Один эпизод не стирает предыдущую работу. Он показывает сильную Связку и даёт данные для следующего ответа','Relapse-prevention guidance рекомендует пересматривать coping strategy после неудачных попыток, а не превращать единичный эпизод в окончательный приговор.','abstinence_violation','B','Relapse-prevention guidance','NICE NG209 — Treating tobacco dependence','https://www.nice.org.uk/guidance/ng209/chapter/treating-tobacco-dependence',null,array['other'],array['meaning','release_tension'],array['cigarette','hookah','vape'],array['lapse'],array['meaning_read','write_real_need'],true,140,'2026-08-16'),
('can_quit_anytime','Я могу бросить когда захочу','Не нужно спорить с этим. Проще посмотреть на свои данные: какие эпизоды повторяются и насколько легко реально пропустить привычный ответ','ALIVE заменяет спор наблюдением за повторяемостью cue → urge → nicotine response.','control_belief','C','ALIVE behavioural hypothesis','ALIVE Method v1','https://github.com/wd7b3k/Alive/blob/main/docs/METHODOLOGY.md',null,array['spontaneous','other'],array['meaning'],array['cigarette','hookah','vape'],array['control'],array['write_real_need'],true,150,'2026-08-16'),
('too_stressed_to_quit','Сейчас слишком стрессовый период','Страх стать более напряжённым после отказа понятен, но прекращение курения не означает постоянный рост стресса','Stress-related expectancies themselves have been associated with lower odds of abstinence in prospective data; withdrawal support and evidence-based treatment can reduce the burden of a quit attempt.','stress_expectancy','B','Prospective expectancy evidence + withdrawal support','Stress-related expectations about smoking cessation','https://pubmed.ncbi.nlm.nih.gov/28367399/',null,array['tension','anxiety','uncertainty'],array['release_tension','pause'],array['cigarette'],array['stress'],array['five_long_exhales','nrt_gum','walk_two_minutes'],true,160,'2026-08-16'),
('one_of_few_pleasures','Курение — одна из моих немногих радостей','Не нужно отрицать удовольствие. Полезнее разобрать, что именно в нём ценно: никотин, пауза, ожидание, место, вкус или контакт','Positive smoking outcome expectancies связаны с lapse, а preliminary expectancy-challenge research показывает потенциал работы с альтернативными reinforcers.','positive_reinforcement','B','Outcome expectancy evidence; Myth Engine remains experimental','Kaufmann & Haaga 2023','https://pubmed.ncbi.nlm.nih.gov/36356395/','10.1016/j.addbeh.2022.107542',array['boredom','evening','social'],array['pleasure','pause','connection'],array['cigarette','hookah','vape'],array['pleasure','boredom'],array['favorite_song','tea_pause','savor_result'],true,170,'2026-08-16'),
('without_smoking_more_anxious','Без сигарет я навсегда стану тревожнее','Withdrawal может временно быть неприятным, но в долгосрочных данных прекращение курения не связано с ухудшением психического состояния и часто сопровождается улучшением','Важно различать первые withdrawal symptoms и более долгий период после cessation.','mental_health_expectancy','A','Systematic review evidence','Taylor et al. Cochrane 2021','https://pubmed.ncbi.nlm.nih.gov/33687070/','10.1002/14651858.CD013522.pub2',array['anxiety','irritability','tension'],array['release_tension'],array['cigarette'],array['mental_health'],array['ground_feet','five_long_exhales'],true,180,'2026-08-16')
on conflict (code) do update set
  title=excluded.title,short_reframe=excluded.short_reframe,explanation=excluded.explanation,
  mechanism=excluded.mechanism,evidence_level=excluded.evidence_level,evidence_scope=excluded.evidence_scope,
  source_title=excluded.source_title,source_url=excluded.source_url,doi=excluded.doi,
  trigger_codes=excluded.trigger_codes,need_codes=excluded.need_codes,product_types=excluded.product_types,
  context_tags=excluded.context_tags,replacement_codes=excluded.replacement_codes,published=true,
  sort_order=excluded.sort_order,last_verified_at=excluded.last_verified_at;

-- Balanced Facts catalog: risk, mechanism and benefits of cessation are intentionally mixed.
insert into public.facts_catalog
(code,title,short_text,full_text,category,benefit,evidence_level,evidence_kind,source_title,source_url,doi,sample_size,product_types,min_pack_years,context_tags,published,sort_order,last_verified_at)
values
('low_intensity_cvd','Даже одна сигарета — не «почти ноль»','Для сердечно-сосудистого риска уменьшение количества сигарет не работает как простая линейная шкала','Meta-analysis 141 cohort studies показал, что примерно одна сигарета в день несёт непропорционально большую долю excess coronary heart disease/stroke risk относительно 20 сигарет в день. Это population evidence, а не личный прогноз.','heart',false,'A','meta_analysis','Hackshaw et al. BMJ 2018','https://www.bmj.com/content/360/bmj.j5855',null,null,array['cigarette'],null,array['risk','low_intensity'],true,10,'2026-08-16'),
('mortality_decade','Продолжение курения связано с потерей примерно десятилетия жизни','В крупной американской когорте current smokers в среднем теряли более 10 лет жизни по сравнению с never smokers','Это population average из большой cohort study и не предсказывает срок жизни конкретного человека.','mortality',false,'A','prospective_cohort','Jha et al. NEJM 2013','https://www.nejm.org/doi/full/10.1056/NEJMsa1211128','10.1056/NEJMsa1211128',216917,array['cigarette'],null,array['risk'],true,20,'2026-08-16'),
('quit_before_40','Отказ раньше даёт особенно большой выигрыш','В той же крупной когорте отказ до 40 лет устранял большую часть excess mortality, связанной с продолжением курения','Раньше лучше, но это не означает, что после 40 бросать бессмысленно.','mortality',true,'A','prospective_cohort','Jha et al. NEJM 2013','https://www.nejm.org/doi/full/10.1056/NEJMsa1211128','10.1056/NEJMsa1211128',216917,array['cigarette'],null,array['benefit'],true,30,'2026-08-16'),
('heavy_smoker_cvd_5y','Сердечно-сосудистый риск начинает меняться после отказа','У former heavy smokers в JAMA cohort risk cardiovascular disease был ниже уже в первые 5 лет после cessation по сравнению с current smokers','Study included 8 770 participants and defined heavy smoking as at least 20 pack-years. Risk относительно never smokers мог оставаться повышенным существенно дольше.','heart',true,'A','prospective_cohort','Duncan et al. JAMA 2019','https://jamanetwork.com/journals/jama/fullarticle/2748507','10.1001/jama.2019.10298',8770,array['cigarette'],20,array['benefit','heavy_smoking'],true,40,'2026-08-16'),
('mental_health_after_quit','Отказ не означает постоянное ухудшение настроения','Cochrane review не нашёл evidence долгосрочного ухудшения mental health после cessation; по ряду outcomes состояние у бросивших было лучше','Первые недели withdrawal и долгосрочное mental health — не одно и то же.','mental_health',true,'A','systematic_review','Taylor et al. Cochrane 2021','https://pubmed.ncbi.nlm.nih.gov/33687070/','10.1002/14651858.CD013522.pub2',null,array['cigarette'],null,array['benefit','stress'],true,50,'2026-08-16'),
('nrt_safer','НЗТ намного безопаснее продолжения курения','НЗТ даёт никотин без сигаретного дыма и токсичных продуктов горения','Никотин не становится полезным веществом, но тяжёлый вред combustible cigarettes нельзя приравнивать к НЗТ.','treatment',true,'A','guideline_public_health','CDC — Quit Medicines Are Much Safer Than Smoking','https://www.cdc.gov/tobacco/campaign/tips/quit-smoking/quit-smoking-medications/3-reasons-to-use-medicines-when-you-quit/quit-medicines-are-safer-than-smoking/index.html',null,null,array['cigarette'],null,array['nrt','benefit'],true,60,'2026-08-16'),
('light_not_safe','Light не делает сигарету безопасной','Low-tar/light descriptors не означают существенно меньший риск для здоровья','Исторические machine yields и descriptors могут создавать ложную интуицию безопасности.','product',false,'A','surgeon_general','U.S. Surgeon General 2000 highlights','https://archive.cdc.gov/www_cdc_gov/tobacco/sgr/2000/highlights.html',null,null,array['cigarette'],null,array['risk','product'],true,70,'2026-08-16'),
('secondhand_no_safe','Для пассивного табачного дыма нет безопасного уровня воздействия','Secondhand smoke вызывает серьёзные cardiovascular и respiratory последствия','Эта карточка особенно важна, когда курение происходит рядом с другими людьми, но ALIVE не использует её для shame.','others',false,'A','public_health','CDC — About Secondhand Smoke','https://www.cdc.gov/tobacco/secondhand-smoke/about.html',null,null,array['cigarette','hookah'],null,array['others','social'],true,80,'2026-08-16'),
('oral_health','Табак влияет не только на лёгкие','Курение связано с заболеваниями дёсен, потерей зубов и раком полости рта','Внешний вид — только небольшая часть oral-health последствий.','oral_health',false,'A','public_health','CDC — Smoking and Oral Health','https://www.cdc.gov/tobacco/about/cigarettes-and-cardiovascular-disease.html',null,null,array['cigarette'],null,array['oral','risk'],true,90,'2026-08-16'),
('rewards_work','Награды могут реально помогать бросить','Cochrane 2025 нашёл high-certainty evidence, что incentives повышают long-term quit rates','В основном long-term анализе 39 исследований и 18 303 участника: pooled RR 1.52. Это основание для добровольного Freedom Fund, а не для азартной механики.','behavior',true,'A','systematic_review','Notley et al. Cochrane 2025','https://www.cochrane.org/evidence/CD004307_can-rewards-help-people-quit-smoking-and-do-they-work-long-term','10.1002/14651858.CD004307.pub7',18303,array['cigarette'],null,array['reward','benefit'],true,100,'2026-08-16'),
('treatment_plus_support','Поддержка и лекарства работают сильнее вместе','WHO рекомендует сочетать доказательную фармакотерапию с поведенческой поддержкой','ALIVE может быть частью digital support, но не заменяет врача или доказательную cessation care.','treatment',true,'A','guideline','WHO Clinical Treatment Guideline 2024','https://www.who.int/publications/i/item/9789240096431',null,null,array['cigarette','hookah'],null,array['treatment','benefit'],true,110,'2026-08-16'),
('who_medications','Есть несколько доказательных медикаментозных вариантов','WHO рекомендует NRT, varenicline, bupropion и cytisine для tobacco cessation','Выбор конкретного препарата и безопасность зависят от человека и инструкции/медицинской консультации.','treatment',true,'A','guideline','WHO Clinical Treatment Guideline 2024','https://www.who.int/publications/i/item/9789240096431',null,null,array['cigarette','hookah'],null,array['treatment'],true,120,'2026-08-16'),
('cues_matter','Окружение может быть сильнее абстрактной силы воли','EMA meta-analysis нашёл сильную within-person связь environmental/social cues с lapse','Поэтому изменение места, последовательности и доступности продукта — не мелочь, а осмысленная behavioural target.','behavior',true,'B','systematic_review_meta_analysis','Perski et al. Addiction 2023','https://pubmed.ncbi.nlm.nih.gov/36807443/','10.1111/add.16173',null,array['cigarette'],null,array['cues','behavior'],true,130,'2026-08-16'),
('craving_is_signal','Тяга — изменяющееся состояние, а не приказ','В EMA studies momentary craving связан с lapse, но сам факт тяги не означает неизбежное курение','ALIVE использует этот момент как точку вмешательства: заметить контекст и попробовать другой ответ.','behavior',true,'B','systematic_review_meta_analysis','Perski et al. Addiction 2023','https://pubmed.ncbi.nlm.nih.gov/36807443/','10.1111/add.16173',null,array['cigarette'],null,array['craving','behavior'],true,140,'2026-08-16'),
('expectancies_predict_lapse','Обещание сигареты — часть зависимости','Positive smoking outcome expectancies в EMA research предсказывали first lapse на следующий день','Это одна из причин, почему ALIVE отдельно работает с Мифами и сравнивает ожидание с реальным outcome.','behavior',true,'B','ecological_momentary_assessment','Gwaltney et al. 2005','https://pubmed.ncbi.nlm.nih.gov/16351387/','10.1037/0021-843X.114.4.661',305,array['cigarette'],null,array['myths','behavior'],true,150,'2026-08-16'),
('digital_support','Цифровая поддержка может быть частью отказа','WHO допускает text messaging, smartphone apps и internet programmes как adjunct или self-management tools','Это не означает, что любое приложение автоматически эффективно: конкретный продукт должен доказать собственную ценность.','behavior',true,'A','guideline','WHO Clinical Treatment Guideline 2024','https://www.who.int/publications/i/item/9789240096431',null,null,array['cigarette','hookah'],null,array['digital','benefit'],true,160,'2026-08-16'),
('weight_varies','Набор веса после отказа не одинаков у всех','Средний post-cessation gain существует, но individual variation очень большая','Вес можно рассматривать как отдельную задачу питания и движения, не как аргумент продолжать inhaled tobacco smoke.','weight',true,'A','meta_analysis','BMJ — Weight gain in smokers after quitting cigarettes','https://www.bmj.com/content/345/bmj.e4439',null,null,array['cigarette'],null,array['weight'],true,170,'2026-08-16'),
('lapse_is_data','Один эпизод не обязан становиться возвратом к старому режиму','После эпизода полезнее разобрать trigger, need и следующий coping response, чем объявлять попытку законченной','ALIVE сознательно не использует «день ноль» как наказание и сохраняет предыдущие данные.','behavior',true,'B','guideline','NICE NG209 — Treating tobacco dependence','https://www.nice.org.uk/guidance/ng209/chapter/treating-tobacco-dependence',null,null,array['cigarette','hookah','vape'],null,array['lapse','benefit'],true,180,'2026-08-16')
on conflict (code) do update set
  title=excluded.title,short_text=excluded.short_text,full_text=excluded.full_text,category=excluded.category,
  benefit=excluded.benefit,evidence_level=excluded.evidence_level,evidence_kind=excluded.evidence_kind,
  source_title=excluded.source_title,source_url=excluded.source_url,doi=excluded.doi,sample_size=excluded.sample_size,
  product_types=excluded.product_types,min_pack_years=excluded.min_pack_years,context_tags=excluded.context_tags,
  published=true,sort_order=excluded.sort_order,last_verified_at=excluded.last_verified_at;
